from typing import List

from data_to_model.generators.dataclass_generator import DataClassGenerator
from data_to_model.models import ClassData, ClassField


expected_data_class = """# This file was generated by data_to_model.
from dataclasses import dataclass
from typing import Any, Dict, List


@dataclass
class TestClass:
    field1: int
    field2: float
    field3: bool
    field4: str
    field5: List

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TestClass":
        field1 = int(data["Field1"])
        field2 = float(data["Field2"])
        field3 = data["Field3"]
        field4 = str(data["Field4"])
        field5 = data["Field5"]
        return cls(field1=field1, field2=field2, field3=field3, field4=field4, field5=field5)

    def to_dict(self) -> Dict[str, Any]:
        return {"Field1": self.field1, "Field2": self.field2, "Field3": self.field3, "Field4": self.field4, "Field5": self.field5}

"""


def test_dataclass_generator(data_class_simple: ClassData):
    dataclass_generator = DataClassGenerator([data_class_simple])
    file_content = dataclass_generator.generate_file_content()
    assert file_content.content == expected_data_class


def test_generate_dict_getter(class_fields_simple: List[ClassField]):
    expected_outputs = [
        'field1 = int(data["Field1"])',
        'field2 = float(data["Field2"])',
        'field3 = data["Field3"]',
        'field4 = str(data["Field4"])',
        'field5 = data["Field5"]',
    ]
    for field, output in zip(class_fields_simple, expected_outputs):
        getter = DataClassGenerator.generate_dict_getter(field)
        assert getter == output
